FROM ubuntu:16.04

RUN mkdir -p /opt
WORKDIR /opt

# change source mirror site
RUN sed -i 's|http://archive.ubuntu.com|http://mirror1.ku.ac.th|g' /etc/apt/sources.list

# update
RUN apt-get update
RUN apt-get install -y build-essential apt-utils curl autoconf automake libxmu-dev
RUN apt-get upgrade -y

